// <auto-generated />
using System;
using COMP2084_a1_shoestore.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace COMP2084_a1_shoestore.Migrations
{
    [DbContext(typeof(ShoeStoreContext))]
    partial class ShoeStoreContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("COMP2084_a1_shoestore.Models.Album", b =>
                {
                    b.Property<int>("ShoeTypeId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Brand");

                    b.Property<int>("FootwearId");

                    b.Property<string>("Name");

                    b.Property<DateTime>("ReleaseDate");

                    b.HasKey("ShoeTypeId");

                    b.HasIndex("FootwearId");

                    b.ToTable("ShoeType");
                });

            modelBuilder.Entity("COMP2084_a1_shoestore.Models.Footwear", b =>
                {
                    b.Property<int>("FootwearId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("FootwearId");

                    b.ToTable("Footwear");
                });

            modelBuilder.Entity("COMP2084_a1_shoestore.Models.Shoe", b =>
                {
                    b.Property<int>("ShoeId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ShoeTypeId");

                    b.Property<string>("Brand");

                    b.Property<string>("Color");

                    b.Property<int>("Size");

                    b.Property<string>("ShoeName");

                    b.HasKey("ShoeId");

                    b.HasIndex("ShoeTypeId");

                    b.ToTable("Shoe");
                });

            modelBuilder.Entity("COMP2084_a1_shoestore.Models.ShoeType", b =>
                {
                    b.HasOne("COMP2084_a1_shoestore.Models.Footwear")
                        .WithMany("ShoeType")
                        .HasForeignKey("FootwearId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("COMP2084_a1_shoestore.Models.Shoe", b =>
                {
                    b.HasOne("COMP2084_a1_shoestore.Models.ShoeType")
                        .WithMany("Shoes")
                        .HasForeignKey("ShoeTypeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
